name: MacPriceTickerIOS
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
targets:
  MacPriceTickerIOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
      - path: Shared
      - path: Resources
    info:
      path: Config/App-Info.plist
      properties:
        CFBundleDisplayName: MacPriceTicker
        CoinGeckoAPIKey: CG-zyozjT2fd1BopjhPMAMbqCAi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fiowind.macpriceticker.ios
        PRODUCT_NAME: MacPriceTickerIOS
        PRODUCT_DISPLAY_NAME: MacPriceTicker
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: MacPriceTickerWidget
        embed: true

  MacPriceTickerWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Widget
      - path: Shared
    info:
      path: Config/Widget-Info.plist
      properties:
        CFBundleDisplayName: MacPriceTicker
        CoinGeckoAPIKey: CG-zyozjT2fd1BopjhPMAMbqCAi
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fiowind.macpriceticker.ios.widget
        PRODUCT_NAME: MacPriceTickerWidget
        PRODUCT_DISPLAY_NAME: MacPriceTicker
        GENERATE_INFOPLIST_FILE: NO
        APPLICATION_EXTENSION_API_ONLY: YES
        SKIP_INSTALL: YES

schemes:
  MacPriceTickerIOS:
    build:
      targets:
        MacPriceTickerIOS: all
        MacPriceTickerWidget: all
